meta:
  image: pojntfx/ipxebuilderd:latest
  dev: false
  debugPort: 31441
  debugNodePort: 31442
  target: "{{ .DIBS_TARGET }}"
  platform: "{{ .TARGETPLATFORM }}"
  debug: "{{ .DIBS_DEBUG }}"

resources:
  memory: "1Gi"
  cpu: "800m"
  maxReplicas: 10

ingress:
  nodePort: 31440
  domain: ipxebuilderd.felix.pojtinger.com
  path: /

S3:
  bucket: ipxebuilderd
  secure: false

minio:
  ingress:
    enabled: true
    hosts:
      - name: minio.ipxebuilderd.felix.pojtinger.com
  accessKey:
    password: ipxebuilderUser
  secretKey:
    password: ipxebuilderPassword
